spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./hohistar-con-data
    username: sa
    password:
  jpa:
    database: H2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /api/h2
      settings:
        web-allow-others: true
